name: cvmaker
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bottom_navy_bar: null
  cupertino_icons: null
  email_validator: null
  firebase_auth: ^3.1.1
  flutter:
    sdk: flutter
  font_awesome_flutter: null
  google_sign_in: 
  lite_rolling_switch: null
  percent_indicator: null
  provider: 
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/logo.png
    - asset/Arabic.png
    - asset/English.png
    - asset/bg.png
    - asset/store.png
    - asset/Asset 1.png
    - asset/Asset 2.png
    - asset/Asset 3.png
    - asset/Asset 4.png
    - asset/Asset 5.png
    - asset/Asset 6.png
    - asset/Asset 7.png
    - asset/illustration.png
    - asset/logos/facebook.jpg
    - asset/logos/google.jpg
    - asset/logos/github.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: asset/fonts/OpenSans.ttf
