name: cvmaker
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bottom_navy_bar: null
  cupertino_icons: null

  font_awesome_flutter: null
  lite_rolling_switch: null
  percent_indicator: null
  shared_preferences: any
  email_validator: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/logo.png
    - asset/Arabic.png
    - asset/English.png
    - asset/bg.png
    - asset/store.png
    - asset/Asset 1.png
    - asset/Asset 2.png
    - asset/Asset 3.png
    - asset/Asset 4.png
    - asset/Asset 5.png
    - asset/Asset 6.png
    - asset/Asset 7.png
    - asset/illustration.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
